random-xs:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
random-xs-clustered:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
msspacev-1M:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
msturing-1M:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
msspacev-10M:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M-clustered:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-30M-clustered:
    cufe:
      docker-tag: neurips23-congestion-cufe
      module: neurips23.congestion.cufe.cufe
      constructor: diskannCUFE
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16},
             {"R":32, "L":70, "insert_threads":16, "consolidate_threads":16},
             {"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":70, "T":16}]
