random-xs:
  candy_lshapg:
    docker-tag: neurips23-streaming-candy_lshapg
    module: neurips23.streaming.candy_lshapg.candy_lshapg
    constructor: candy_lshapg
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "LSHAPG"}]
        query-args: |
            [{"ef":30}]
msturing-10M-clustered:
  candy_lshapg:
    docker-tag: neurips23-streaming-candy_lshapg
    module: neurips23.streaming.candy_lshapg.candy_lshapg
    constructor: candy_lshapg
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "LSHAPG"}]
        query-args: |
          [{"ef":30}]
