random-xs:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
random-xs-clustered:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
msspacev-1M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
msturing-1M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
msspacev-10M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M-clustered:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-30M-clustered:
    diskann: 
      docker-tag: neurips23-streaming-diskann
      module: neurips23.streaming.diskann.diskann-str
      constructor: diskann
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16},
             {"R":32, "L":70, "insert_threads":16, "consolidate_threads":16},
             {"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":70, "T":16}]
