text2image-10M:
    scann:
      docker-tag: neurips23-ood-scann
      module: neurips23.ood.scann.scann
      constructor: Scann
      base-args: ["@metric"]
      run-groups:
        tree40k-config0:
          args: |
            [{"tree_size": 40000, "download": true, "config_id": 0}]
          query-args: |
            [{"leaves_to_search": 35, "reorder": 150}]
        tree40k-config1:
          args: |
            [{"tree_size": 40000, "download": true, "config_id": 1}]
          query-args: |
            [{"leaves_to_search": 42, "reorder": 160}]
        tree40k-config2:
          args: |
            [{"tree_size": 40000, "download": true, "config_id": 2}]
          query-args: |
            [{"leaves_to_search": 27, "reorder": 140}]
