random-xs:
  faiss_pq:
    docker-tag: neurips23-streaming-faiss_pq
    module: neurips23.streaming.faiss_pq.faiss_pq
    constructor: faiss_pq
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "PQ4x8np"}]
        query-args: |
            [{"ef":30}]
msturing-10M-clustered:
  faiss_lsh:
    docker-tag: neurips23-streaming-faiss_pq
    module: neurips23.streaming.faiss_pq.faiss_pq
    constructor: faiss_pq
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"indexkey": "PQ8x8np"}]
        query-args: |
          [{"ef":30}]
