# Contributed by @GuilhemN in https://github.com/erikbern/ann-benchmarks/pull/233
name: Billion-Scale ANN Benchmarks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - algorithm: faiss-ivf
            library: faissconda
            dataset: random-xs
          - algorithm: faiss-t1
            dataset: random-xs
            library: faissconda
          - algorithm: faiss-t1
            dataset: random-range-xs
            library: faissconda
          - algorithm: diskann-t2
            dataset: random-xs
            library: diskann
          - algorithm: diskann-t2
            dataset: random-range-xs
            library: diskann
          - algorithm: bbann
            dataset: random-xs
            library: bbann
          - algorithm: bbann
            dataset: random-range-xs
            library: bbann
          - algorithm: httpann_example
            dataset: random-xs
            library: httpann_example
          - algorithm: httpann_example
            dataset: random-range-xs
            library: httpann_example
      fail-fast: false

    steps:
    - uses: actions/checkout@v2 # Pull the repository

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python install.py
      env:
        LIBRARY: ${{ matrix.library }}
        DATASET: ${{ matrix.dataset }}

    - name: Run the benchmark
      run: |
        python create_dataset.py --dataset $DATASET
        python run.py --algorithm $ALGORITHM --max-n-algorithms 2 --dataset $DATASET --timeout 600
        sudo chmod -R 777 results/
        python plot.py --dataset $DATASET --output plot.png
        python data_export.py --output test.csv

      env:
        ALGORITHM: ${{ matrix.algorithm}}
        DATASET: ${{ matrix.dataset }} 
