msturing-30M-clustered:
    quake: 
      docker-tag: neurips23-streaming-quake
      module: neurips23.streaming.quake.quake_wrapper
      constructor: quake
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{ "batch_size" : 10000, "build_args" : { "nlist" : 1000, "search_workers" : 8}, "mainteance_args" : {"split_threshold" : 2750, "delete_threshold" : 2250, "reduction_threshold" : 0.22, "min_partition_size" : 1024} }]
          query-args: |
            [{ "search_args" : {"search_fraction" : 0.115, "batch_size" : 2500} }]